### ISSUE TITLE
Incremental replication on serial column not retrieving last record

### ISSUE THREAD

**Issue by malleblas** [omniti-labs/mimeo#11]
**Source**
Version string	PostgreSQL 9.3.4, compiled by Visual C++ build 1600, 32-bit

**Destination**
Version string	PostgreSQL 9.1.11 on x86_64-pc-linux-gnu, compiled by x86_64-pc-linux-gnu-gcc (Gentoo 4.7.3-r1 p1.4, pie-0.5.5) 4.7.3, 64-bit

*SELECT mimeo.refresh_inserter('schema.table')* or *SELECT mimeo.refresh_inserter('schema.table', null, true)* it fails to retrieve the last record. In this case, the *max(id)* in the destination table is *332000*, the table *mimeo.refresh_config_inserter_serial* has as the *last_value==332000* but the source table has a *max(id)==332100*. My sequence is incrementing by 100 (this is because there are numerous sources and to avoid id collision, this is my work around).

**Comment by malleblas** [comment]
A quick note, I put -1 in the boundary column and now it behaves as I would expect, however I think that perhaps it should be boundary set to 0, will give you the latest, rather than one less.

**Comment by keithf4** [comment]
If the values on the column you are using as the control are always completely unique, you should be fine doing this. However, if they are not, you risk missing data if replication happens to run at the time inserts are being done and that integer value has not finished inserting all the rows that contain it. See the documentation on the p_boundary value on any of the maker functions.
If have this set at the default of 1 to ensure people setting things up using the default values do not accidentally miss any data. Yes this means that the latest value will not always be on the destination. But it ensures no data is ever missed.
