### ISSUE TITLE
(Question) Many sources for one destination for logdel replication

### ISSUE THREAD

**Issue by lefan** [omniti-labs/mimeo#14]
Am I understanding correct, that:
It is not possible to configure many sources tables to replicate in one destination table for `logdel` replication?
Should I use things like PGSQL INHERITS features for such configuration?

**Comment by keithf4** [comment]
It's not possible to configure multiple source tables for any replication method in mimeo. I have no means of conflict resolution for conflicting writes and adding that is far more complexity than I want to add to mimeo at this time.
If you can find some way around it with inheritance for your setup, go for it.
