### ISSUE TITLE
(Question) ERROR: »foo« is not a view

### ISSUE THREAD

**Issue by dseitz** [omniti-labs/mimeo#18]
I'm trying to setup a snapshot replication but when running `SELECT mimeo.snapshot_maker('public.foo', 1);` the error **ERROR: »foo« is not a view** is thrown.

I'm using Debian with PostgreSQL 9.1.15. The table to replicate looks like this:

    CREATE TABLE foo (
        f_id serial NOT NULL,
        ...
        CONSTRAINT foo_pkey PRIMARY KEY (f_id)
    );

The following commands were executed (as user postgres):

    destinationdb=# CREATE EXTENSION dblink;
    destinationdb=# CREATE SCHEMA mimeo;
    destinationdb=# CREATE EXTENSION pg_jobmon SCHEMA mimeo;
    destinationdb=# CREATE EXTENSION mimeo SCHEMA mimeo;
    destinationdb=# GRANT EXECUTE ON ALL FUNCTIONS IN SCHEMA mimeo TO postgres;
    destinationdb=# INSERT INTO mimeo.dblink_mapping_mimeo (data_source, username, pwd) VALUES ('host=localhost port=5432 dbname=sourcedb', 'postgres', 'password');
    destinationdb=# SELECT mimeo.snapshot_maker('public.foo', 1);
    NOTICE:  ALTER TABLE / ADD PRIMARY KEY will create implicit index "foo_snap1_f_id_pk" for table "foo_snap1"
    CONTEXT:  SQL statement "ALTER TABLE public.foo_snap1 ADD CONSTRAINT foo_snap1_f_id_pk PRIMARY KEY ("f_id")"
    PL/pgSQL function "create_index" line 82 at EXECUTE statement
    SQL statement "SELECT create_index(v_dest_table, v_src_schema_name, v_src_table_name, v_snap, p_debug)"
    PL/pgSQL function "refresh_snap" line 338 at PERFORM
    SQL statement "SELECT mimeo.refresh_snap('public.foo', p_index := true, p_pulldata := true, p_debug := false)"
    PL/pgSQL function "snapshot_maker" line 74 at EXECUTE statement
    ERROR:  "foo" is not a view

What did I do wrong? Can Mimeo only replicate views?

**Comment by keithf4** [comment]
Does the destination table already exist? It cannot exist already when setting up snapshot replication (see doc file for snapshot_maker()). 
Could probably put a check in that maker function to avoid the confusing error.

**Comment by dseitz** [comment]
Yes, the destination table was already existing. After I dropped the table the replication worked perfectly.
Where is the doc file for snapshot_maker()? I have searched the repository but couldn't find anything. Sorry, I don't have much experience regarding this things.
Thank you.

**Comment by keithf4** [comment]
https://github.com/omniti-labs/mimeo/blob/master/doc/mimeo.md

**Comment by dseitz** [comment]
Thanks. I really should start looking harder.

**Comment by keithf4** [comment]
FYI, I've pushed out version 1.4.4 which has a fix for snapshot_maker() to give a clearer error when the destination table exists. Thanks for bringing it to my attention!
